[package]
name = "cleaner-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "dxtr-cleaner-gui"
path = "src/main.rs"

[dependencies]
cleaner-core.workspace = true
cleaner-macos.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
